---
- name: Ansible Deployment
  hosts: all

  roles:
    - install_packages
    - dnf_update

  tasks:
    - name: Get hostname
      debug:
        msg: '{{ ansible_hostname }}'
      tags:
        - debug
