- name: Create job for each location
  awx.awx.job_template:
    name: "{{ item.name }} Nodes"
    job_type: "run"
    organization: "Default"
    inventory: "{{ item.name }}"
    project: "{{ project_name }}"
    playbook: "{{ playbook }}"
    credentials:
      - "Host Credentials"
    job_tags: "debug"
    execution_environment: AWX EE (latest)
    state: "present"
  loop: "{{ vars.inventory }}"

- name: Create job to configure OLAM
  awx.awx.job_template:
    name: 1 - Configure OLAM
    job_type: "run"
    organization: "Default"
    inventory: OLAM Server
    project: "{{ project_name }}"
    playbook: configure-olam.yml
    state: "present"

- name: Create job to check the time
  awx.awx.job_template:
    name: Maintenance Window
    job_type: "run"
    organization: "Default"
    inventory: OLAM Server
    project: "{{ project_name }}"
    playbook: mx-window.yml
    state: "present"

- name: Create job to apply updates
  awx.awx.job_template:
    name: Upgrade all packages in {{ item.name }}
    job_type: "run"
    organization: "Default"
    inventory: "{{ item.name }}"
    credentials:
      - "Host Credentials"
    project: "{{ project_name }}"
    playbook: playbook.yml
    job_tags: "debug"
    state: "present"
  loop: "{{ vars.inventory }}"