- name: Create job for each location
  awx.awx.job_template:
    name: "{{ item.name }} Nodes"
    job_type: "run"
    organization: "Default"
    inventory: "{{ item.name }}"
    project: "{{ project_name }}"
    playbook: "{{ playbook }}"
    credentials:
      - "Host Credentials"
    job_tags: "debug"
    execution_environment: AWX EE (latest)
    state: "present"
  loop: "{{ vars.inventory }}"

- name: Create job to configure OLAM
  awx.awx.job_template:
    name: 1 - Configure OLAM
    job_type: "run"
    organization: "Default"
    inventory: OLAM Server
    project: "{{ project_name }}"
    playbook: configure-olam.yml
    state: "present"

- name: Create job to check the time
  awx.awx.job_template:
    name: Maintenance Window
    job_type: "run"
    organization: "Default"
    inventory: OLAM Server
    project: "{{ project_name }}"
    playbook: mx-window.yml
    state: "present"

- name: Create job to apply updates
  awx.awx.job_template:
    name: Upgrade all packages in {{ item.name }}
    job_type: "run"
    organization: "Default"
    inventory: "{{ item.name }}"
    credentials:
      - "Host Credentials"
    project: "{{ project_name }}"
    playbook: playbook.yml
    job_tags: "dnf_update"
    state: "present"
  loop: "{{ vars.inventory }}"

- name: Create job to run reposync on ULN mirror
  awx.awx.job_template:
    name: Run Repo Sync on ULN Mirror
    job_type: "run"
    organization: "Default"
    inventory: ULN Mirror
    credentials:
      - "Host Credentials"
    project: "{{ project_name }}"
    playbook: playbook.yml
    job_tags: "reposync"
    state: "present"

- name: Create job that allows user to run ad-hoc commands on remote systems
  awx.awx.job_template:
    name: Execute commands on remote systems
    job_type: "run"
    organization: "Default"
    ask_inventory_on_launch: true
    project: "{{ project_name }}"
    playbook: playbook.yml
    credentials:
      - "Host Credentials"
    job_tags: "ad_hoc_command"
    state: "present"
    survey_enabled: yes
    survey_spec: "{{ lookup('file', 'ad_hoc_command.json') }}"